package edison

var miniboardPinMap = map[string]sysfsPin{
	"J17-1": sysfsPin{
		pin:          182,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-2": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-3": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-4": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-5": sysfsPin{
		pin:          135,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-6": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-7": sysfsPin{
		pin:          27,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-8": sysfsPin{
		pin:          20,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-9": sysfsPin{
		pin:          28,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-10": sysfsPin{
		pin:          111,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-11": sysfsPin{
		pin:          109,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-12": sysfsPin{
		pin:          115,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-13": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-14": sysfsPin{
		pin:          128,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-1": sysfsPin{
		pin:          13,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-2": sysfsPin{
		pin:          165,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-3": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-4": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-5": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-6": sysfsPin{
		pin:          19,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-7": sysfsPin{
		pin:          12,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-8": sysfsPin{
		pin:          183,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-9": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-10": sysfsPin{
		pin:          110,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-11": sysfsPin{
		pin:          114,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-12": sysfsPin{
		pin:          129,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-13": sysfsPin{
		pin:          130,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-14": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-1": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-2": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-3": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-4": sysfsPin{
		pin:          44,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-5": sysfsPin{
		pin:          46,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-6": sysfsPin{
		pin:          48,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-7": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-8": sysfsPin{
		pin:          131,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-9": sysfsPin{
		pin:          14,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-10": sysfsPin{
		pin:          40,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-11": sysfsPin{
		pin:          43,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-12": sysfsPin{
		pin:          77,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-13": sysfsPin{
		pin:          82,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-14": sysfsPin{
		pin:          83,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},

	"J20-1": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-2": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-3": sysfsPin{
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-4": sysfsPin{
		pin:          45,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-5": sysfsPin{
		pin:          47,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-6": sysfsPin{
		pin:          49,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-7": sysfsPin{
		pin:          15,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-8": sysfsPin{
		pin:          84,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-9": sysfsPin{
		pin:          42,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-10": sysfsPin{
		pin:          41,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-11": sysfsPin{
		pin:          78,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-12": sysfsPin{
		pin:          79,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-13": sysfsPin{
		pin:          80,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-14": sysfsPin{
		pin:          81,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
}
