package edison

var sparkfunPinMap = map[string]sysfsPin{
	"12": sysfsPin{
		pin:          12,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"13": sysfsPin{
		pin:          13,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"14": sysfsPin{
		pin:          14,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"15": sysfsPin{
		pin:          15,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"44": sysfsPin{
		pin:          44,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"45": sysfsPin{
		pin:          45,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"46": sysfsPin{
		pin:          46,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"47": sysfsPin{
		pin:          47,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"48": sysfsPin{
		pin:          48,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"49": sysfsPin{
		pin:          49,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"128": sysfsPin{
		pin:          128,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"129": sysfsPin{
		pin:          129,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"130": sysfsPin{
		pin:          130,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"131": sysfsPin{
		pin:          131,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"182": sysfsPin{
		pin:          182,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"183": sysfsPin{
		pin:          183,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
}
