package edison

var miniboardPinMap = map[string]sysfsPin{
	"J17-1": {
		pin:          182,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-2": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-3": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-4": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-5": {
		pin:          135,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-6": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-7": {
		pin:          27,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-8": {
		pin:          20,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-9": {
		pin:          28,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-10": {
		pin:          111,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-11": {
		pin:          109,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-12": {
		pin:          115,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-13": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J17-14": {
		pin:          128,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-1": {
		pin:          13,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-2": {
		pin:          165,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-3": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-4": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-5": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-6": {
		pin:          19,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-7": {
		pin:          12,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-8": {
		pin:          183,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-9": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-10": {
		pin:          110,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-11": {
		pin:          114,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-12": {
		pin:          129,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-13": {
		pin:          130,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J18-14": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-1": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-2": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-3": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-4": {
		pin:          44,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-5": {
		pin:          46,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-6": {
		pin:          48,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-7": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-8": {
		pin:          131,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-9": {
		pin:          14,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-10": {
		pin:          40,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-11": {
		pin:          43,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-12": {
		pin:          77,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-13": {
		pin:          82,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J19-14": {
		pin:          83,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},

	"J20-1": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-2": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-3": {
		pin:          -1,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-4": {
		pin:          45,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-5": {
		pin:          47,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-6": {
		pin:          49,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-7": {
		pin:          15,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-8": {
		pin:          84,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-9": {
		pin:          42,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-10": {
		pin:          41,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-11": {
		pin:          78,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-12": {
		pin:          79,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-13": {
		pin:          80,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"J20-14": {
		pin:          81,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
}
