package edison

var sparkfunPinMap = map[string]sysfsPin{
	"12": {
		pin:          12,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"13": {
		pin:          13,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"14": {
		pin:          14,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"15": {
		pin:          15,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"44": {
		pin:          44,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"45": {
		pin:          45,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"46": {
		pin:          46,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"47": {
		pin:          47,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"48": {
		pin:          48,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"49": {
		pin:          49,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"128": {
		pin:          128,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"129": {
		pin:          129,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"130": {
		pin:          130,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"131": {
		pin:          131,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"182": {
		pin:          182,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
	"183": {
		pin:          183,
		resistor:     -1,
		levelShifter: -1,
		pwmPin:       -1,
		mux:          []mux{},
	},
}
