// Code generated by "stringer -type=AS5600StatusType"; DO NOT EDIT.

package i2c

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[as5600MagnetNotDetected-0]
	_ = x[as5600MagnetTooWeak-1]
	_ = x[as5600MagnetOk-2]
	_ = x[as5600MagnetTooStrong-3]
	_ = x[as5600MagnetUnknown-4]
}

const _AS5600StatusType_name = "as5600MagnetNotDetectedas5600MagnetTooWeakas5600MagnetOkas5600MagnetTooStrongas5600MagnetUnknown"

var _AS5600StatusType_index = [...]uint8{0, 23, 42, 56, 77, 96}

func (i AS5600StatusType) String() string {
	if i >= AS5600StatusType(len(_AS5600StatusType_index)-1) {
		return "AS5600StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AS5600StatusType_name[_AS5600StatusType_index[i]:_AS5600StatusType_index[i+1]]
}
